services:
  proxy:
    image: haproxy:2.7.10-alpine
    hostname: proxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - mynet

  frontend:
    build: .
    hostname: frontend
    ports:
      - 3001:3001
    networks:
      - mynet

  db:
    build:
      context: .
      dockerfile: ./Dockerfile-DB
    hostname: db
    ports:
      - 3000:3000
    networks:
      - mynet

networks:
  mynet:
    driver: bridge